modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="cookingforblockheads"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="cookingforblockheads.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[dependencies.cookingforblockheads]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.cookingforblockheads]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.cookingforblockheads]]
modId="balm"
mandatory=true
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
