package net.blay09.mods.cookingforblockheads.fabric.datagen;

import net.blay09.mods.balm.world.level.block.DeferredBlock;
import net.blay09.mods.cookingforblockheads.block.ModBlocks;
import net.blay09.mods.cookingforblockheads.tag.ModBlockTags;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagsProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.TagKey;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends FabricTagsProvider.BlockTagsProvider {
    public ModBlockTagProvider(FabricPackOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected void addTags(HolderLookup.Provider arg) {
        final var mineablePickaxeTag = tag(TagKey.create(Registries.BLOCK, Identifier.withDefaultNamespace("mineable/pickaxe")));
        ModBlocks.cookingTables.sortedValues().map(DeferredBlock::asResourceKey).forEach(mineablePickaxeTag::add);
        ModBlocks.sinks.sortedValues().map(DeferredBlock::asResourceKey).forEach(mineablePickaxeTag::add);
        ModBlocks.chickenSinks.sortedValues().map(DeferredBlock::asResourceKey).forEach(mineablePickaxeTag::add);
        ModBlocks.counters.sortedValues().map(DeferredBlock::asResourceKey).forEach(mineablePickaxeTag::add);
        ModBlocks.cabinets.sortedValues().map(DeferredBlock::asResourceKey).forEach(mineablePickaxeTag::add);
        ModBlocks.connectors.sortedValues().map(DeferredBlock::asResourceKey).forEach(mineablePickaxeTag::add);
        ModBlocks.fridges.sortedValues().map(DeferredBlock::asResourceKey).forEach(mineablePickaxeTag::add);
        ModBlocks.ovens.sortedValues().map(DeferredBlock::asResourceKey).forEach(mineablePickaxeTag::add);
        ModBlocks.kitchenFloors.sortedValues().map(DeferredBlock::asResourceKey).forEach(mineablePickaxeTag::add);
        mineablePickaxeTag.add(ModBlocks.toaster.asResourceKey(), ModBlocks.coffeeMachine.asResourceKey(), ModBlocks.milkJar.asResourceKey(), ModBlocks.cowJar.asResourceKey(), ModBlocks.cookieJar.asResourceKey());

        final var mineableAxeTag = tag(TagKey.create(Registries.BLOCK, Identifier.withDefaultNamespace("mineable/axe")));
        mineableAxeTag.add(ModBlocks.toolRack.asResourceKey(), ModBlocks.spiceRack.asResourceKey(), ModBlocks.fruitBasket.asResourceKey(), ModBlocks.cuttingBoard.asResourceKey());

        final var kitchenItemProviders = tag(ModBlockTags.KITCHEN_ITEM_PROVIDERS);
        kitchenItemProviders.add(ModBlocks.toolRack.asResourceKey());
        ModBlocks.chickenSinks.sortedValues().map(DeferredBlock::asResourceKey).forEach(kitchenItemProviders::add);
        ModBlocks.cabinets.sortedValues().map(DeferredBlock::asResourceKey).forEach(kitchenItemProviders::add);
        ModBlocks.counters.sortedValues().map(DeferredBlock::asResourceKey).forEach(kitchenItemProviders::add);
        kitchenItemProviders.add(ModBlocks.cookieJar.asResourceKey());

        final var rawKitchenItemProviders = getOrCreateRawBuilder(ModBlockTags.KITCHEN_ITEM_PROVIDERS);
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("farmersdelight", "basket"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("farmersdelight", "pantry"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "oak_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "spruce_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "birch_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "jungle_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "acacia_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "dark_oak_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "crimson_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "warped_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "mangrove_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "framed_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "oak_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "spruce_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "birch_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "jungle_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "acacia_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "dark_oak_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "crimson_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "warped_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "mangrove_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "framed_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "oak_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "spruce_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "birch_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "jungle_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "acacia_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "dark_oak_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "crimson_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "warped_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "mangrove_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "framed_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "autumnity_maple_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_willow_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_cherry_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_wisteria_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_rosewood_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_morado_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_yucca_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_kousa_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_aspen_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_grimwood_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "upgrade_aquatic_driftwood_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "upgrade_aquatic_river_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "endergetic_poise_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "bayou_blues_cypress_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "abundance_jacaranda_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "abundance_redbud_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "autumnity_stripped_maple_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_stripped_willow_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_stripped_cherry_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_stripped_wisteria_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_rosewood_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_morado_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_yucca_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_kousa_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_aspen_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_grimwood_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "upgrade_aquatic_stripped_driftwood_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "upgrade_aquatic_stripped_river_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "endergetic_stripped_poise_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "bayou_blues_stripped_cypress_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "abundance_stripped_jacaranda_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "abundance_stripped_redbud_cabinet"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "autumnity_maple_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_willow_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_cherry_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_wisteria_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_rosewood_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_morado_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_yucca_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_kousa_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_aspen_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_grimwood_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "upgrade_aquatic_driftwood_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "upgrade_aquatic_river_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "endergetic_poise_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "bayou_blues_cypress_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "abundance_jacaranda_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "abundance_redbud_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "autumnity_stripped_maple_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_stripped_willow_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_stripped_cherry_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_stripped_wisteria_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_rosewood_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_morado_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_yucca_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_kousa_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_aspen_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_grimwood_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "upgrade_aquatic_stripped_driftwood_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "upgrade_aquatic_stripped_river_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "endergetic_stripped_poise_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "bayou_blues_stripped_cypress_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "abundance_stripped_jacaranda_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "abundance_stripped_redbud_kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "kitchen_drawer"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "barrel"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "iron_barrel"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "gold_barrel"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "diamond_barrel"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "netherite_barrel"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_barrel_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_iron_barrel_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_gold_barrel_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_diamond_barrel_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_netherite_barrel_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_barrel_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_iron_barrel_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_gold_barrel_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_diamond_barrel_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_netherite_barrel_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_barrel_3"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_iron_barrel_3"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_gold_barrel_3"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_diamond_barrel_3"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_netherite_barrel_3"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_barrel_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_iron_barrel_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_gold_barrel_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_diamond_barrel_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_netherite_barrel_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "chest"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "iron_chest"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "gold_chest"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "diamond_chest"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "netherite_chest"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "shulker_box"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "iron_shulker_box"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "gold_shulker_box"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "diamond_shulker_box"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "netherite_shulker_box"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "oak_full_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "oak_full_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "oak_full_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "oak_half_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "oak_half_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "oak_half_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "spruce_full_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "spruce_full_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "spruce_full_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "spruce_half_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "spruce_half_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "spruce_half_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "birch_full_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "birch_full_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "birch_full_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "birch_half_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "birch_half_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "birch_half_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "jungle_full_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "jungle_full_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "jungle_full_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "jungle_half_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "jungle_half_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "jungle_half_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "acacia_full_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "acacia_full_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "acacia_full_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "acacia_half_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "acacia_half_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "acacia_half_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "dark_oak_full_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "dark_oak_full_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "dark_oak_full_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "dark_oak_half_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "dark_oak_half_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "dark_oak_half_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "mangrove_full_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "mangrove_full_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "mangrove_full_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "mangrove_half_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "mangrove_half_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "mangrove_half_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "cherry_full_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "cherry_full_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "cherry_full_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "cherry_half_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "cherry_half_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "cherry_half_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "bamboo_full_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "bamboo_full_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "bamboo_full_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "bamboo_half_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "bamboo_half_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "bamboo_half_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "crimson_full_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "crimson_full_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "crimson_full_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "crimson_half_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "crimson_half_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "crimson_half_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "warped_full_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "warped_full_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "warped_full_drawers_4"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "warped_half_drawers_1"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "warped_half_drawers_2"));
        rawKitchenItemProviders.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "warped_half_drawers_4"));

        final var cookingTables = tag(ModBlockTags.COOKING_TABLES);
        ModBlocks.cookingTables.sortedValues().map(DeferredBlock::asResourceKey).forEach(cookingTables::add);

        final var counters = tag(ModBlockTags.COUNTERS);
        ModBlocks.counters.sortedValues().map(DeferredBlock::asResourceKey).forEach(counters::add);

        final var cabinets = tag(ModBlockTags.CABINETS);
        ModBlocks.cabinets.sortedValues().map(DeferredBlock::asResourceKey).forEach(cabinets::add);

        final var fridges = tag(ModBlockTags.FRIDGES);
        ModBlocks.fridges.sortedValues().map(DeferredBlock::asResourceKey).forEach(fridges::add);

        final var ovens = tag(ModBlockTags.OVENS);
        ModBlocks.ovens.sortedValues().map(DeferredBlock::asResourceKey).forEach(ovens::add);

        final var sinks = tag(ModBlockTags.SINKS);
        ModBlocks.sinks.sortedValues().map(DeferredBlock::asResourceKey).forEach(sinks::add);

        final var chickenSinks = tag(ModBlockTags.CHICKEN_SINKS);
        ModBlocks.chickenSinks.sortedValues().map(DeferredBlock::asResourceKey).forEach(chickenSinks::add);

        final var kitchenConnectors = tag(ModBlockTags.KITCHEN_CONNECTORS);
        ModBlocks.connectors.sortedValues().map(DeferredBlock::asResourceKey).forEach(kitchenConnectors::add);
        ModBlocks.kitchenFloors.sortedValues().map(DeferredBlock::asResourceKey).forEach(kitchenConnectors::add);

        final var rawKitchenConnectors = getOrCreateRawBuilder(ModBlockTags.KITCHEN_CONNECTORS);
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_oak_andesite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_oak_diorite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_oak_granite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_oak_blackstone"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_spruce_andesite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_spruce_diorite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_spruce_granite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_spruce_blackstone"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_birch_andesite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_birch_diorite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_birch_granite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_birch_blackstone"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_jungle_andesite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_jungle_diorite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_jungle_granite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_jungle_blackstone"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_acacia_andesite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_acacia_diorite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_acacia_granite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_acacia_blackstone"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_dark_oak_andesite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_dark_oak_diorite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_dark_oak_granite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_dark_oak_blackstone"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_warped_andesite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_warped_diorite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_warped_granite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_warped_blackstone"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_crimson_andesite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_crimson_diorite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_crimson_granite"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "counter_crimson_blackstone"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cupboard_oak"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cupboard_spruce"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cupboard_birch"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cupboard_jungle"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cupboard_acacia"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cupboard_dark_oak"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cupboard_warped"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cupboard_crimson"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cabinet_oak"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cabinet_birch"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cabinet_spruce"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cabinet_jungle"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cabinet_acacia"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cabinet_dark_oak"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cabinet_warped"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "cabinet_crimson"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "shelf_oak"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "shelf_birch"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "shelf_spruce"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "shelf_jungle"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "shelf_acacia"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "shelf_dark_oak"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "shelf_crimson"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("buildersaddition", "shelf_warped"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "storage_controller"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "storage_extension"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "autumnity_maple_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_willow_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_cherry_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_wisteria_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_rosewood_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_morado_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_yucca_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_kousa_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_aspen_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_grimwood_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "upgrade_aquatic_driftwood_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "upgrade_aquatic_river_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "endergetic_poise_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "bayou_blues_cypress_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "abundance_jacaranda_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "abundance_redbud_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "autumnity_stripped_maple_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_stripped_willow_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_stripped_cherry_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "environmental_stripped_wisteria_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_rosewood_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_morado_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_yucca_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_kousa_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_aspen_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "atmospheric_stripped_grimwood_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "upgrade_aquatic_stripped_driftwood_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "upgrade_aquatic_stripped_river_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "endergetic_stripped_poise_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "bayou_blues_stripped_cypress_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "abundance_stripped_jacaranda_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("morecfm", "abundance_stripped_redbud_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "kitchen_sink"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "oak_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "spruce_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "birch_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "jungle_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "acacia_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "dark_oak_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "stripped_oak_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "stripped_spruce_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "stripped_birch_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "stripped_jungle_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "stripped_acacia_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "stripped_dark_oak_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "white_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "orange_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "magenta_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "light_blue_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "yellow_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "lime_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "pink_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "gray_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "light_gray_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "cyan_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "purple_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "blue_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "brown_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "green_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "red_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("cfm", "black_kitchen_counter"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "controller"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "storage_link"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "controller_slave"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "controller"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "oak_trim"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "spruce_trim"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "birch_trim"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "jungle_trim"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "acacia_trim"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "dark_oak_trim"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "warped_trim"));
        rawKitchenConnectors.addOptionalElement(Identifier.fromNamespaceAndPath("storagedrawers", "crimson_trim"));
    }
}
