@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.cookingforblockheads.compat;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;