[versions]
balm = "26.2.0.1-SNAPSHOT"
shogi = "26.1.2.2-SNAPSHOT"
minecraft = "26.2-snapshot-5"
neoForm = "26.2-snapshot-5-1"
neoForge = "26.1.1.15-beta"
forge = "63.0.2"
fabricApi = "0.147.1+26.2"
fabricLoader = "0.19.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.10", version = "2025.10.12" }

balmCommon = { module = "net.blay09.mods:balm-common", version.ref = "balm" }
balmNeoForge = { module = "net.blay09.mods:balm-neoforge", version.ref = "balm" }
balmForge = { module = "net.blay09.mods:balm-forge", version.ref = "balm" }
balmFabric = { module = "net.blay09.mods:balm-fabric", version.ref = "balm" }
shogiApi = { module = "net.blay09.mods:shogi-api", version.ref = "shogi" }

neoForm = { module = "net.neoforged:neoform", version.ref = "neoForm" }
neoForge = { module = "net.neoforged:neoforge", version.ref = "neoForge" }
forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }

mixin = { module = "org.spongepowered:mixin", version = "0.8.7" }

[plugins]
fabricLoom = { id = "net.fabricmc.fabric-loom", version = "1.14-SNAPSHOT" }
modDevGradle = { id = "net.neoforged.moddev", version = "2.0.141" }
forgeGradle = { id = "net.minecraftforge.gradle", version = "[7,8)" }
mixin = { id = "org.spongepowered.mixin", version = "0.7-SNAPSHOT" }
curseForgeGradle = { id = "net.darkhax.curseforgegradle", version = "1.1.26" }
modrinthMinotaur = { id = "com.modrinth.minotaur", version = "2.+" }
