[versions]
balm = "26.1.0.1-SNAPSHOT"
minecraft = "26.1-rc-2"
neoForm = "26.1-rc-2-1"
neoForge = "26.1.0.0-alpha.15+pre-3"
forge = "61.0.3"
fabricApi = "0.144.0+26.1"
fabricLoader = "0.18.4"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.10", version = "2025.10.12" }

balmCommon = { module = "net.blay09.mods:balm-common", version.ref = "balm" }
balmNeoForge = { module = "net.blay09.mods:balm-neoforge", version.ref = "balm" }
balmForge = { module = "net.blay09.mods:balm-forge", version.ref = "balm" }
balmFabric = { module = "net.blay09.mods:balm-fabric", version.ref = "balm" }

neoForm = { module = "net.neoforged:neoform", version.ref = "neoForm" }
neoForge = { module = "net.neoforged:neoforge", version.ref = "neoForge" }
forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }

mixin = { module = "org.spongepowered:mixin", version = "0.8.7" }

[plugins]
fabricLoom = { id = "net.fabricmc.fabric-loom", version = "1.14-SNAPSHOT" }
modDevGradle = { id = "net.neoforged.moddev", version = "2.0.140" }
forgeGradle = { id = "net.minecraftforge.gradle", version = "[7,8)" }
mixin = { id = "org.spongepowered.mixin", version = "0.7-SNAPSHOT" }
curseForgeGradle = { id = "net.darkhax.curseforgegradle", version = "1.1.26" }
modrinthMinotaur = { id = "com.modrinth.minotaur", version = "2.+" }
