@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.cookingforblockheads.registry.recipe;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;